version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=rms
      - POSTGRES_USER=rms
      - POSTGRES_PASSWORD=rms
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "python /code/manage.py migrate && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - web-data:/code
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  db-data:
  web-data:
