# Generated by Django 2.0.1 on 2018-03-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_auto_20180316_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationInstanceMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rms.Instance')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='instances',

        ),
        migrations.AddField(
            model_name='reservation',
            name='instances',
            field=models.ManyToManyField(through='rms.ReservationInstanceMembership', to='rms.Instance'),
        ),
        migrations.AddField(
            model_name='reservationinstancemembership',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rms.Reservation'),
        ),
    ]
