# Generated by Django 2.0.1 on 2018-03-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0003_auto_20180321_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='inventory_number',
            field=models.CharField(max_length=200, unique=True, verbose_name='Inventarnummer'),
        ),
    ]
