# Generated by Django 2.0.1 on 2018-03-26 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0004_auto_20180322_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationCheckoutInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rms.Instance')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rms.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationClearedInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField()),
                ('checkin_date', models.DateTimeField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rms.Instance')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rms.Reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='checked_in_instances',
            field=models.ManyToManyField(related_name='checked_in_reservations', through='rms.ReservationClearedInstance', to='rms.Instance'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checked_out_instances',
            field=models.ManyToManyField(related_name='checked_out_reservations', through='rms.ReservationCheckoutInstance', to='rms.Instance'),
        ),
    ]
