# Generated by Django 2.0.1 on 2018-04-04 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0005_auto_20180326_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rms.Reservation')),
            ],
        ),
    ]
