# Generated by Django 2.0.1 on 2018-04-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0006_checkoutticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('amount', models.IntegerField(verbose_name='Anzahl')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abstract_items', to='rms.Reservation')),
            ],
        ),
    ]
