# Generated by Django 2.0.1 on 2018-04-06 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0007_abstractitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractitem',
            name='checkout_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
