# Generated by Django 2.0.1 on 2018-05-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0008_abstractitem_checkout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
