# Generated by Django 2.0.5 on 2018-05-09 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0010_device_active'),
    ]

    operations = [
            migrations.RunSQL("ALTER TABLE rms_instance ALTER COLUMN serial_number DROP NOT NULL;"),
    ]
