# Generated by Django 3.1.6 on 2021-02-16 00:18

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0012_auto_20180906_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'permissions': (('view_unrentable', 'Can view unrentable inventory'),)},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={},
        ),
        migrations.AlterField(
            model_name='device',
            name='price_new',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=20, verbose_name='Neupreis'),
        ),
        migrations.AlterField(
            model_name='device',
            name='price_rental',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=20, verbose_name='Vermietpreis'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='rentable',
            field=models.BooleanField(default=True, verbose_name='Ausleihbar'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='warehouse',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rms.warehouse', verbose_name='Lagerort'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Bezeichnung'),
        ),
    ]
