# Generated by Django 3.2.3 on 2021-05-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0013_auto_20210216_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Nachname'),
        ),
    ]
