# Generated by Django 3.2.3 on 2021-05-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0014_auto_20210516_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='title',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default=0, max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
